Add support for domain param
nearform/fastify-casbin-rest pull request #14
Opened 2021-02-15 22:07 UTC by kibertoad

fixes #5 
See https://github.com/casbin/node-casbin/blob/master/examples/rbac_with_domains_model.conf

2021-02-15 22:21 UTC, simoneb reviewed
Wouldn't this all be much simpler if we left the "dom" part as the last parameter of every operation supported by the plugin? It would just be a fourth parameter that's optional everywhere.

By doing that, the signatures wold be preserved, instead of changing based on whether `getDom` is provided or not, meaning that the code would end up being more obvious and simple.

2021-02-15 22:27 UTC, kibertoad commented
@simoneb Yup, did that for everything but enforcer, but problem with also structuring enforcer call that way is that it would contradict casbin-idiomatic way of going from more broad into more narrow parts of policy left to right. See this for an example: https://casbin.org/docs/en/rbac-with-domains
Forcing users to rewrite their policies in a way that differs from all documentation and examples out there and also is not intuitive for the sake of simplification of a plugin doesn't seem right.

2021-02-15 22:28 UTC, kibertoad commented
@simoneb I can, however, restructure code a bit so that the majority of code is shared and passes dom always, regardless of whether it is undefined or not, and only enforcer call is different. Would that be better?

2021-02-15 22:29 UTC, simoneb commented
Ah that's a fair point actually. On the other hand, changing the signatures of this plugin depending on the presence of that parameter doesn't sound great either. Do you see any other options? My concern is that this plugin becomes too confusing to use, which is something I'd like to avoid.

2021-02-15 22:30 UTC, simoneb commented
> @simoneb I can, however, restructure code a bit so that the majority of code is shared and passes dom always, regardless of whether it is undefined or not, and only enforcer call is different. Would that be better?

It would certainly be better yes, unless we have a different option altogether, even at the code of introducing a breaking change and releasing a new major.

2021-02-15 22:35 UTC, kibertoad commented
@simoneb Please take a look at a new version, I think it looks much better :)

2021-02-16 07:32 UTC, simoneb approved these changes
One comment about the logging but otherwise LGTM. I'm still not a fan of these changing signatures but I understand why you're doing it this way, and I agree with the principle.

2021-02-16 07:32 UTC, simoneb commented on plugin.js
> +  log: (fastify, request, sub, obj, act, _dom) => { fastify.log.info({ sub, obj, act }, 'Invoking casbin enforce') },
this is not a sensible default. either we always log it (simple solution), or we log it conditionally, if provided

2021-02-16 08:21 UTC, mcollina requested changes

2021-02-16 08:21 UTC, mcollina commented on plugin.js
> +        const dom = getDom(request)
I think `getDom()` should not be called if not set from the options.

2021-02-16 08:24 UTC, simoneb commented
@kibertoad while you're here, please add yourself to the list of contributors in package.json

2021-02-16 15:57 UTC, kibertoad commented on plugin.js
> +        const dom = getDom(request)
@mcollina That was the case originally, but @simoneb requested more consistent behaviour regardless of configuration.
@simoneb Do you prefer conditionally invoking `getDom` (more branching) or invoking no-op getter by default (less branching, more calls)?

2021-02-16 21:32 UTC, simoneb commented on plugin.js
> +        const dom = getDom(request)
let's do conditional invocation of this, yes. we should strike a balance between consistency and performance. in this case avoiding a function call is probably preferable if not needed, especially because this is invoked every time the route handler is executed

2021-02-16 21:33 UTC, simoneb commented on plugin.js
> +  getDom: (_request) => undefined,
as mentioned in another comment, let's not give this a default

2021-02-16 21:34 UTC, simoneb commented on plugin.js
> +        const isAuthorized = dom ? await fastify.casbin.enforce(sub, dom, obj, act) : await fastify.casbin.enforce(sub, obj, act)
I think the condition here is based on whether getDom has a value, rather than dom. if getDom is provided, regardless of whether it returns a truthy value or not, we invoke enforce with 4 arguments.

2021-02-16 21:35 UTC, simoneb commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
this is the kind of inconsistency I don't like very much. dom appearing after sub in some cases, and at the end in others. as mentioned, I understand why you decided to do it this way but as I user I would find this quite confusing

2021-02-17 13:22 UTC, kibertoad commented
@mcollina @simoneb I believe I've addressed all the comments so far, please let me know if anything else is left!

2021-02-17 13:34 UTC, simoneb approved these changes

2021-02-17 14:16 UTC, kibertoad commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
We can do a semver major and always put dom in the middle, would that be better?

2021-02-17 14:24 UTC, simoneb commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
not really. we would have to make it conditional in the same way as you did with enforce, but I'm not sure it's worth it

2021-02-19 12:51 UTC, kibertoad commented
@mcollina Sorry for pinging you, but maybe you could take a look?

2021-03-02 17:46 UTC, kibertoad commented
@simoneb Maybe we can proceed with this PR?

2021-03-02 21:24 UTC, simoneb commented
let's get @mcollina's approval first

2021-03-03 09:16 UTC, mcollina commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
I think the best approach is to move away from positional arguments and use a wrapping object.

2021-03-03 09:43 UTC, simoneb commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
@kibertoad are you happy to make this semver major change?

2021-03-03 09:44 UTC, kibertoad commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
sure! will do the change shortly

2021-03-03 09:47 UTC, simoneb commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
thanks. I guess this will open up quite a few possibilities beyond what the plugin is currently doing. if we don't use positional parameters I believe we could create an options object which parameters named in any way, meaning that we could support any casbin model. this would probably not really fit into a "rest" model anymore, but I guess it would be fine

2021-03-03 09:49 UTC, kibertoad commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
How would you determine order in which parameters would be passed to enforcer, though?

2021-03-03 09:59 UTC, simoneb commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
insertion order is guaranteed for string properties in ES2015, I think we can safely rely on that. nevertheless, you don't have to make this larger change, we can keep the well-known names

2021-03-03 10:02 UTC, mcollina commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
I would keep the well-known names.

2021-03-04 20:18 UTC, kibertoad commented on plugin.js
> +          await options.onDeny(reply, sub, obj, act, dom)
@simoneb @mcollina Changes made!

2021-03-05 08:17 UTC, simoneb commented on plugin.d.ts
> +export type Permission = { sub: string, dom?: string, obj: string, act: string}
```suggestion
export type Permission = { sub: string, dom?: string, obj: string, act: string }
```

2021-03-05 08:17 UTC, simoneb commented on test/plugin.test-d.ts
> +server.delete<ListRequest>('/', {
why this change?

2021-03-05 08:17 UTC, simoneb commented on test/casbinRest.test.js
> +    getDom: (_request) => 'common'
naming consistency

```suggestion
    getDom: (request) => 'common'
```

2021-03-05 08:17 UTC, simoneb commented on test/casbinRest.test.js
> +  t.plan(5)
isn't it better to keep a test which checks that both scenarios are supported: with and without dom?

2021-03-05 08:46 UTC, mcollina commented on plugin.js
> +  log: (fastify, request, permission) => { fastify.log.info(permission, 'Invoking casbin enforce') },
```suggestion
  log: (fastify, request, permission) => { request.log.info(permission, 'Invoking casbin enforce') },
```

2021-03-05 08:47 UTC, mcollina commented
code is good for me.

2021-03-05 08:51 UTC, kibertoad commented on test/plugin.test-d.ts
> +server.delete<ListRequest>('/', {
Don't remember, and I don't think there is any difference, so I'll change back to get

2021-03-05 08:53 UTC, kibertoad commented on test/casbinRest.test.js
> +  t.plan(5)
done

2021-03-05 08:56 UTC, simoneb approved these changes

2021-03-05 09:08 UTC, mcollina approved these changes
lgtm

2021-03-05 09:14 UTC, merged

2021-03-05 09:16 UTC, kibertoad commented
@simoneb Thanks! Could you publish a new version?

2021-03-05 10:11 UTC, simoneb commented
released major v2